### ISSUE TITLE
Add issue templates

### ISSUE THREAD

**Issue by mominsid** [reactables/reactables#83]
Using other open source projects as inspiration, I think it would be good to generate issue templates that are appropriate to the project, and to recommend issue authors to use those templates.

Some examples in the wild:

- https://github.com/jaredpalmer/formik/tree/main/.github/ISSUE_TEMPLATE
- More examples to be researched?

**Comment by laidav** [comment]
Completed by https://github.com/reactables/reactables/commit/6eb7d7176fe5631fb14a20bfb09bca2f697c35f7
